/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/navbar";
import data from "../../json/data.json";

import { Barlow_Condensed, Bellefair } from "@next/font/google";
import { useState } from "react";

import { PageTitle } from "../components/pageTitle";

const barlow_condensed = Barlow_Condensed({
  weight: ["300", "500"],
  subsets: ["latin"],
});

const bellefair = Bellefair({ weight: "400", subsets: ["latin"] });

const CrewPage: NextPage = () => {
  const [currentCrew, setCurrentCrew] = useState(0);

  return (
    <>
      <Head>
        <title>Space Tourism | Crew</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>
      <main
        className="flex min-h-screen 
        flex-col justify-start
        bg-[url('/assets/crew/background-crew-mobile.jpg')] bg-cover md:bg-[url('/assets/crew/background-crew-tablet.jpg')] lg:bg-[url('/assets/crew/background-crew-desktop.jpg')]"
      >
        <Navbar currentPage="crew" />
        <PageTitle pNumber="02" pTitle="Meet your crew" />
        <section className="mx-auto flex w-3/4 flex-row">
          <section className="flex basis-1/2 flex-col justify-center">
            <h2
              className={`text-3xl uppercase text-white text-opacity-50 ${bellefair.className} mb-4 font-light`}
            >
              {data.crew[currentCrew]?.role}
            </h2>
            <h3
              className={`${bellefair.className} mb-8 text-5xl uppercase text-white`}
            >
              {data.crew[currentCrew]?.name}
            </h3>
            <p
              className={`text-[#D0D6F9] ${barlow_condensed.className} font-light tracking-wide`}
            >
              {data.crew[currentCrew]?.bio}
            </p>
          </section>
          {/* <img
            className="max-w-[514px] basis-1/2"
            src={data.crew[currentCrew]?.images.webp}
            alt={data.crew[currentCrew]?.name}
          /> */}
        </section>
      </main>
    </>
  );
};

export default CrewPage;
