import { type NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/navbar";
import { PageTitle } from "../components/pageTitle";

const TechnologyPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Space Tourism | Technology</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>
      <main
        className="flex min-h-screen 
        flex-col
        bg-[url('/assets/technology/background-technology-mobile.jpg')] bg-cover md:bg-[url('/assets/technology/background-technology-tablet.jpg')] lg:bg-[url('/assets/technology/background-technology-desktop.jpg')]"
      >
        <Navbar currentPage="technology" />
        <PageTitle pNumber="03" pTitle="Space Launch 101" />
      </main>
    </>
  );
};

export default TechnologyPage;
